version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    command: start --tunnel
    environment:
      - GENERIC_TIMEZONE=America/Fortaleza
      - TZ=America/Fortaleza
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:

# docker compose up -d
# http://localhost:5678

#docker compose logs
#docker compose logs -f

#docker compose down